### ISSUE TITLE
Elisp, GPL?

### ISSUE THREAD

**Issue by alphapapa** [philjackson/wordy-date#5]
Hi @philjackson,

I just stumbled upon this library (having just re-stumbled upon `xmlgen` thanks to its being mentioned in an EmacsConf 2020 presentation).  Its code looks impressively simple, and it looks incredibly useful.

Since you're also an Elisper, I wonder: would you be interested in an Elisp port of this library?  And would you be willing to also license it under the GPL, which would make it easier to integrate with Emacs and Emacs packages?  (I guess--I see that the FSF seems to approve of the Eclipse Public License, but I haven't looked at the details.)

Thanks for your work.

**Comment by philjackson** [comment]
Hey, @alphapapa. Thanks for reaching out. This library stands on the rather massive shoulders of the Instaparse library - I'm not sure it has an elisp equivalent but either way I'm not sure I'd be up for doing a port myself to be honest. Of course people are welcome to port it themselves and use whichever license they deem appropriate.

Which talk was xmlgen mentioned in, btw?

**Comment by alphapapa** [comment]
Ah, I overlooked the use of Instaparse.  Maybe the Emacs packages `peg` or `parsec` could be used in its place, or even one of the built-in Emacs parsing-related libraries.  Well, maybe I'll look into that sometime.  :)

I can't remember which talk mentioned it, but it may have been Corwin Brust's, in which he showed how he generates SVGs in Emacs.  Or it might have been the talk by Brett Gilio about org-webring.

Thanks.
